name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

    - name: Build Docker image
      run: docker build -t varsubham/cicd-pipeline:latest .

    - name: Push image to DockerHub
      run: docker push varsubham/cicd-pipeline:latest
